name: Share Files Between Jobs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create build output
        run: |
          mkdir -p build
          echo "Hello from build job" > build/message.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/   # this folder will be stored by GitHub

  use-artifact:
    runs-on: ubuntu-latest
    needs: build   # waits for build job
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Read file from previous job
        run: |
          echo "Contents of message.txt:"
          cat build/message.txt
